apiVersion: v1
kind: Service
metadata:
  name: laravel-app-demo
spec:
  ports:
  - nodePort: 31276
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: laravel-app-demo
  type: NodePort